'use client';
import {useMemo,useState} from 'react';
import ResumeUpload from '../components/ResumeUpload';
const features=[['ATS Match','Compare your resume against a job description and surface missing keywords.'],['Tailored Resume','Focus your resume on the role while preserving only your real experience.'],['Cover Letter','Build a role-specific letter grounded in your resume.'],['Application Tracker','Keep jobs, stages and next actions organized in one place.']];
const stop=new Set('the a an and or to of in for with on at by from is are be as this that you your our we they their will can should must have has job role work experience skills years using about into'.split(' '));
function words(s:string){return [...new Set((s.toLowerCase().match(/[a-z][a-z+#.-]{2,}/g)||[]).filter(w=>!stop.has(w)))];}
export default function Home(){
 const [job,setJob]=useState(''); const [resume,setResume]=useState(''); const [ran,setRan]=useState(false);
 const result=useMemo(()=>{const jw=words(job),rw=new Set(words(resume)); const matched=jw.filter(w=>rw.has(w)); const missing=jw.filter(w=>!rw.has(w)); const score=jw.length?Math.round(matched.length/jw.length*100):0; return {score,matched:matched.slice(0,12),missing:missing.slice(0,12)}},[job,resume]);
 function analyze(){if(job.trim().length<80||resume.trim().length<80){alert('Add a fuller job description and resume first.');return}setRan(true);setTimeout(()=>document.getElementById('results')?.scrollIntoView({behavior:'smooth'}),50)}
 return <main><nav><b>HIREVORA</b><a href="/auth">Sign in / Start free</a></nav><section className="hero"><span className="pill">AI CAREER COPILOT</span><h1>Apply smarter.<br/>Get noticed. Get hired.</h1><p>Turn one master resume into a focused application package for every opportunity—without inventing experience.</p><div className="actions"><a className="primary" href="#start">Build my application</a><a className="secondary" href="#features">See how it works</a></div></section><section id="features" className="grid">{features.map(([t,d],i)=><article key={t}><small>0{i+1}</small><h2>{t}</h2><p>{d}</p></article>)}</section><section id="start" className="builder"><div><span className="pill">FIRST APPLICATION</span><h2>Start with the job you want.</h2><p>Paste a job description and your master resume. Hirevora checks overlap first. It never claims experience you did not provide.</p></div><div><form onSubmit={e=>{e.preventDefault();analyze()}}><label>Job description<textarea value={job} onChange={e=>setJob(e.target.value)} placeholder="Paste the full job posting here…" /></label><label>Resume<ResumeUpload onText={setResume}/><span className="or">OR PASTE RESUME TEXT</span><textarea value={resume} onChange={e=>setResume(e.target.value)} placeholder="Paste your current resume here…" /></label><button type="submit">Analyze match →</button><small>Your text stays in this browser during this MVP analysis.</small></form>{ran&&<section id="results" className="results"><div className="score"><strong>{result.score}%</strong><span>keyword overlap</span></div><div><h3>Found in your resume</h3><p>{result.matched.length?result.matched.join(' · '):'No strong matches found yet.'}</p><h3>Job-posting terms to review</h3><p>{result.missing.length?result.missing.join(' · '):'Strong overlap. Review the posting for context and requirements.'}</p><small>Missing terms are not instructions to add qualifications you do not have. Only use truthful experience.</small></div></section>}</div></section><footer>HIREVORA <span>Apply smarter. Get noticed. Get hired.</span></footer></main>
}